name: Unit Tests

on:
    pull_request:
        types: [opened]

jobs:
    build:
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                node: ['10']
        name: Run unit tests
        steps:
            - uses: actions/checkout@v1
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              working-directory: ./frontend
              run: |
                  npm install

            - name: Run unit tests
              working-directory: ./frontend
              run: |
                  npm run test:unit
